#ifndef __ColorRampLayerRenderCtrl__
#define __ColorRampLayerRenderCtrl__

/**
@file
Subclass of ColorRampLayerRenderCtrlBase, which is generated by wxFormBuilder.
*/

#include "ColorRampLayerRenderCtrlBase.h"
#include "ILayerRenderCtrl.h"

//// end generated include

/** Implementing ColorRampLayerRenderCtrlBase */
class ColorRampLayerRenderCtrl : public ColorRampLayerRenderCtrlBase, public ILayerRenderCtrl
{
public:
	/** Constructor */
	ColorRampLayerRenderCtrl(wxWindow* parent);
	//// end generated class members

public:
	// Í¨¹ý ILayerRenderCtrl ¼Ì³Ð
	virtual const char * GetLayerRenderName() override;

	virtual bool IsSupportLayerExactly(ILayer * layer) override;

	virtual bool IsSupportLayer(ILayer * layer) override;

	virtual void SetLayer(ILayer * layer) override;

	virtual void UpdateLayerRender() override;

private:
	void SetDataset(MyGDALRasterDataset* raster);
	void SetLayerRender(RasterColorRampLayerRender* render);

private:
	RasterColorRampLayerRender* _render;
	MyGDALRasterDataset* _raster;
	ILayer* _layer;
};

#endif // __ColorRampLayerRenderCtrl__
