#ifndef __GrayScaleLayerRenderCtrl__
#define __GrayScaleLayerRenderCtrl__

/**
@file
Subclass of GrayScaleLayerRenderCtrlBase, which is generated by wxFormBuilder.
*/

#include "GrayScaleLayerRenderCtrlBase.h"
#include "ILayerRenderCtrl.h"

//// end generated include

/** Implementing GrayScaleLayerRenderCtrlBase */
class GrayScaleLayerRenderCtrl : public GrayScaleLayerRenderCtrlBase, public ILayerRenderCtrl
{
public:
	/** Constructor */
	GrayScaleLayerRenderCtrl(wxWindow* parent);
	//// end generated class members

public:
	// Í¨¹ý ILayerRenderCtrl ¼Ì³Ð
	virtual const char * GetLayerRenderName() override;

	virtual bool IsSupportLayerExactly(ILayer * layer) override;

	virtual bool IsSupportLayer(ILayer * layer) override;

	virtual void SetLayer(ILayer * layer) override;

	virtual void UpdateLayerRender() override;

private:
	void SetDataset(MyGDALRasterDataset* raster);
	void SetLayerRender(RasterGrayScaleLayerRender* render);

private:
	RasterGrayScaleLayerRender* _render;
	MyGDALRasterDataset* _raster;
	ILayer* _layer;
};

#endif // __GrayScaleLayerRenderCtrl__
