#ifndef __PaletteColorDialog__
#define __PaletteColorDialog__

/**
@file
Subclass of PaletteColorDialogBase, which is generated by wxFormBuilder.
*/

#include "PaletteColorDialogBase.h"

//// end generated include

/** Implementing PaletteColorDialogBase */
class PaletteColorDialog : public PaletteColorDialogBase
{
	public:
		/** Constructor */
		PaletteColorDialog( wxWindow* parent );
	//// end generated class members

public:
	void SetPaletteColor(int entry, unsigned char r, unsigned char g, unsigned char b);
	bool GetPaletteColor(int *entry, unsigned char *r, unsigned char *g, unsigned char *b);
};

#endif // __PaletteColorDialog__
