#ifndef __RgbLayerRenderCtrl__
#define __RgbLayerRenderCtrl__

/**
@file
Subclass of RgbLayerRenderCtrlBase, which is generated by wxFormBuilder.
*/

#include "RgbLayerRenderCtrlBase.h"

//// end generated include

#include "ILayerRenderCtrl.h"
#include "tGis_wxGuiCfg.h"

using namespace tGis::Core;

/** Implementing RgbLayerRenderCtrlBase */
class RgbLayerRenderCtrl : public RgbLayerRenderCtrlBase, public ILayerRenderCtrl
{
public:
	/** Constructor */
	RgbLayerRenderCtrl(wxWindow* parent);
	~RgbLayerRenderCtrl();
	//// end generated class members

public:
	// Í¨¹ý ILayerRenderCtrl ¼Ì³Ð
	virtual const char* GetLayerRenderName() override;
	virtual bool IsSupportLayerExactly(ILayer * layer) override;
	virtual bool IsSupportLayer(ILayer * layer) override;
	virtual void SetLayer(ILayer * layer) override;
	virtual void UpdateLayerRender() override;

private:
	void SetDataset(MyGDALRasterDataset* raster);
	void SetLayerRender(RasterRgbLayerRender* render);

private:
	RasterRgbLayerRender* _render;
	MyGDALRasterDataset* _raster;
	ILayer* _layer;

private:
	void _sldOpacity_scroll(wxCommandEvent& event);
};

#endif // __RgbLayerRenderCtrl__
