#ifndef __StandaloneToolDialog__
#define __StandaloneToolDialog__

/**
@file
Subclass of StandaloneToolDialogBase, which is generated by wxFormBuilder.
*/

#include "StandaloneToolDialogBase.h"

//// end generated include

#include "tGis_wxGuiCfg.h"

using namespace tGis::Core;

/** Implementing StandaloneToolDialogBase */
class StandaloneToolDialog : public StandaloneToolDialogBase
{
public:
	/** Constructor */
	StandaloneToolDialog(wxWindow* parent, ToolKit* kit = nullptr);
	//// end generated class members
	~StandaloneToolDialog();

public:
	wxString GetBelong()
	{
		return _txtBelong->GetValue();
	}

	StandaloneTool& GetStandaloneTool()
	{
		return _tool;
	}

private:
	StandaloneTool _tool;

private:
	void _btnAddParam_Click(wxCommandEvent& event);
	void _btnDelParam_Click(wxCommandEvent& event);
	void _lstParam_Selection(wxCommandEvent& event);
	void _sdbSzOK_Clicked(wxCommandEvent& event);
};

#endif // __StandaloneToolDialog__
