#ifndef __VectorUniformLayerRenderCtrl__
#define __VectorUniformLayerRenderCtrl__

/**
@file
Subclass of VectorUniformLayerRenderCtrlBase, which is generated by wxFormBuilder.
*/

#include "VectorUniformLayerRenderCtrlBase.h"

//// end generated include

#include "ILayerRenderCtrl.h"
#include "tGis_wxGuiCfg.h"

using namespace tGis::Core;

BEGIN_NAME_SPACE(tGis, Gui)
class wxSymbolPickerWidget;
END_NAME_SPACE(tGis, Gui)

using namespace tGis::Gui;

/** Implementing VectorUniformLayerRenderCtrlBase */
class VectorUniformLayerRenderCtrl : public VectorUniformLayerRenderCtrlBase, public ILayerRenderCtrl
{
public:
	/** Constructor */
	VectorUniformLayerRenderCtrl(wxWindow* parent);
	~VectorUniformLayerRenderCtrl();
	//// end generated class members

public:
	// Í¨¹ý ILayerRenderCtrl ¼Ì³Ð
	virtual const char* GetLayerRenderName() override;
	virtual bool IsSupportLayerExactly(ILayer * layer) override;
	virtual bool IsSupportLayer(ILayer * layer) override;
	virtual void SetLayer(ILayer * layer) override;
	virtual void UpdateLayerRender() override;

private:
	void SetLayerRender(VectorUniformLayerRender* render);

private:
	VectorUniformLayerRender* _render;
	MyGDALVectorDataset* _vector;
	ILayer* _layer;

private:
	wxSymbolPickerWidget* _markSymPicker;
	wxSymbolPickerWidget* _lineSymPicker;
	wxSymbolPickerWidget* _fillSymPicker;

private:
	void _sldOpacity_scroll(wxCommandEvent& event);
};

#endif // __VectorUniformLayerRenderCtrl__
